Adding JX

diff --git a/files/bashrc b/files/bashrc
--- a/files/bashrc
+++ b/files/bashrc
@@ -5,13 +5,16 @@
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
-export VISUAL=vim
-export EDITOR=vim
+#COREPS1='"\A \[\e[36m\]\u\[\e[0;31m\]@\h\[\e[0;31m\]\[\e[m\]:[\[\e[2m\]\w\[\e[0m\]]"'
+export COREPS1='"\A \[\e[36m\]\$(__k8s_prompt $?)\[\e[0;31m\]\$(__prompt_command)\$(__aws_prompt)\[\e[0;31m\]\[\e[m\]:[\[\e[1;30m\]\w\e[m ]"'
+export VISUAL=vi
+export EDITOR=vi
 export HISTSIZE=10000
 export HISTFILESIZE=50000
 shopt -s histappend
 export HISTCONTROL=ignoreboth:erasedups
 export HISTFILE=$HOME/work/.dock_bash_hist
+source ~/git-prompt.sh
 export AWS_PS1_SHOW=1
 export K8S_PS1_SHOW=0 # Disable the prompt with this var.
 export K8S_PROMT_TTL=15
@@ -28,19 +31,24 @@ source ~/k8s-prompt.sh
 ssha () {
 	if [[ "1" == "$#" ]] ;then
 		ssh -i ~/.ssh/ansible.rsa ansible@$1
-	elif [[ "2" == "$#" ]] ;then
-		ssh -i ~/.ssh/ansible.rsa $2@$1
-	else
+	elif [[ "0" == "$#" ]] ;then
 		>&2 echo "Missing host argument"
+	else
+		targetHost=$1
+		shift
+		ssh -i ~/.ssh/ansible.rsa $@ ansible@$targetHost
 	fi
 }
 
 sshb () {
 	if [[ "1" == "$#" ]] ;then
 		ssh -i ~/.ssh/aws.rsa ec2-user@$1
-	elif [[ "2" == "$#" ]] ;then
-		ssh -i ~/.ssh/aws.rsa $2@$1
+	elif [[ "0" == "$#" ]] ;then
+		>&2 echo "Missing host argument"
 	else
+		targetHost=$1
+		shift
+		ssh -i ~/.ssh/ansible.rsa $@ ansible@$targetHost
 		>&2 echo "Missing host argument"
 	fi
 }
@@ -52,6 +60,17 @@ sshc () {
 	else
 		>&2 echo "Missing host argument"
 	fi
+}
+
+sshia () {
+	if [[ "0" == "$#" ]] ;then
+		>&2 echo "Usage: sshia {host} [extra params]"
+	fi
+	instanceMatch=$(list_instances -r $AWS_DEFAULT_REGION -H ID,State,T:Name,IP,PrivateIP|grep $1|head -1);
+	echo $instanceMatch
+	targetHost=$(echo $instanceMatch |cut -d'|' -f5|cut -d' ' -f2)
+	shift
+	ssh -i ~/.ssh/aws.rsa $@ ansible@$targetHost
 }
 
 ssho () {
@@ -75,8 +94,8 @@ else
            >&2 echo "Environment configuration file ~/env/${TARGET_ENV} does not exist"
         fi
 fi
-export COREPS1='"\A \[\e[36m\]\$(__k8s_prompt $?)\[\e[0;31m\]\$(__prompt_command)\$(__aws_prompt)\[\e[0;31m\]\[\e[m\]:[\[\e[1;30m\]\w\e[m ]"'
 export PREPS1='__git_ps1 '
+export POSPS1=' "\\\$ "'
 export GIT_PS1_SHOWDIRTYSTATE=0
 export GIT_PS1_SHOWSTASHSTATE=0
 export GIT_PS1_SHOWUNTRACKEDFILES=
@@ -85,16 +104,25 @@ export GIT_PS1_DESCRIBE_STYLE="branch"
 export GIT_PS1_SHOWUPSTREAM="auto git"
 #export PS1="${PREPS1}${COREPS1}${POSPS1}"
 export PROMPT_COMMAND="${PREPS1}${COREPS1}${POSPS1}"
-source ~/git-prompt.sh
+no_git_prompt ()
+{
+	export PREPS1=' '
+	export PS1='\A \[\e[36m\]\u\[\e[0;31m\]@\h\[\e[0;31m\]\[\e[m\]:[\[\e[2m\]\w\[\e[0m\]] '
+	unset PROMPT_COMMAND
+}
+git_prompt ()
+{
+	export PS1="${PREPS1}${COREPS1}${POSPS1}"
+}
 
 export GOROOT=/usr/lib/go
 export GOPATH=/home/sre/work/go/workspace
 export GOBIN=$GOROOT/bin
-export PATH="/home/sre/perl5/bin${PATH+:}${PATH}:$GOBIN:$GOPATH:$GOPATH/bin:/usr/lib/ruby/vendor_ruby";
-export PERL5LIB="/home/sre/perl5/lib${PERL5LIB+:}${PERL5LIB}";
-export PERL_LOCAL_LIB_ROOT="/home/sre/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}";
-export PERL_MB_OPT="--install_base \"/home/sre/perl5\"";
-export PERL_MM_OPT="INSTALL_BASE=/home/sre/perl5";
+export PATH="${HOME}/perl5/bin${PATH+:}${PATH}:$GOBIN:$GOPATH:$GOPATH/bin:/usr/lib/ruby/vendor_ruby";
+export PERL5LIB="${HOME}/perl5/lib${PERL5LIB+:}${PERL5LIB}";
+export PERL_LOCAL_LIB_ROOT="${HOME}/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}";
+export PERL_MB_OPT="--install_base \"${HOME}/perl5\"";
+export PERL_MM_OPT="INSTALL_BASE=${HOME}/perl5";
 
 # screen tabs to show the current operation, (i.e. vim, top, etc)
 source ~/preexec.bash.sh
@@ -103,6 +131,16 @@ if [[ $TERM =~ "screen" ]]; then
 	source ~/screen-preexec.sh
 fi
 alias R='R --quiet'
+man() {
+    LESS_TERMCAP_md=$'\e[01;31m' \
+    LESS_TERMCAP_me=$'\e[0m' \
+    LESS_TERMCAP_se=$'\e[0m' \
+    LESS_TERMCAP_so=$'\e[01;44;33m' \
+    LESS_TERMCAP_ue=$'\e[0m' \
+    LESS_TERMCAP_us=$'\e[01;32m' \
+    command man "$@"
+}
+randTagFile () { perl -e '($ml)=(split " ",`wc -l tags`);$rl=int(rand($ml));while(<>){($f)=(split(/\t/))[1] if ($. == $rl)}print "$f\n"' tags; }
 export LANG="en_US"
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/sre/chroot/lib/
 export TERM=xterm-256color
@@ -118,6 +156,7 @@ alias ls='ls --color=auto'
 alias grep='grep --color=auto'
 alias li='list_instances -r $AWS_DEFAULT_REGION -H ID,State,T:Name,IP,PrivateIP'
 alias proveall='prove -j9 --state=slow,save -lr t'
+export PROMPT_DIRTRIM=4
 source ~/utils.sh
 # Add a forced cd to home/work, the default mount location, (by defaut the container drops us to / which is usually undesired.)
 # I guess this will have a bad side effect...
