Fixed ansible bugs, added go back for vim syntax

diff --git a/files/bashrc b/files/bashrc
--- a/files/bashrc
+++ b/files/bashrc
@@ -12,43 +12,55 @@ export HISTFILESIZE=50000
 shopt -s histappend
 export HISTCONTROL=ignoreboth:erasedups
 export HISTFILE=$HOME/work/.dock_bash_hist
+export AWS_PS1_SHOW=1
 export K8S_PS1_SHOW=0 # Disable the prompt with this var.
 export K8S_PROMT_TTL=15
 export K8S_LAST_PROMPT_CHECK=$(($(date +'%s') - $K8S_PROMT_TTL - 1))
 export K8SCTX="unset"
 export K8SNS="unset"
-source ~/k8s-prompt.sh
-export AWS_PS1_SHOW=1
+
+export RET_PS1_SHOW=1
 export K8S_PS1_SHOW=1
 source ~/aws-prompt.sh
+source ~/ret-prompt.sh
+source ~/k8s-prompt.sh
 
 ssha () {
-	if [ $# -eq 1 ]
-	then
-		ssh -i ~/work/git/syseng/vars/keys/ansible_id_rsa ansible@$1
+	if [[ "1" == "$#" ]] ;then
+		ssh -i ~/.ssh/ansible.rsa ansible@$1
+	elif [[ "2" == "$#" ]] ;then
+		ssh -i ~/.ssh/ansible.rsa $2@$1
 	else
 		>&2 echo "Missing host argument"
 	fi
 }
 
 sshb () {
-	if [ $# -eq 1 ]
-	then
-		ssh -i ~/work/git/syseng/vars/keys/aws_initialization_default.pem ec2-user@$1
+	if [[ "1" == "$#" ]] ;then
+		ssh -i ~/.ssh/aws.rsa ec2-user@$1
+	elif [[ "2" == "$#" ]] ;then
+		ssh -i ~/.ssh/aws.rsa $2@$1
 	else
 		>&2 echo "Missing host argument"
 	fi
 }
 
 sshc () {
-	if [ $# -eq 1 ]
-	then
-		ssh -i ~/work/git/syseng/vars/keys/aws_initialization_default.pem admin@$1
+	# kops/CoreOS
+	if [[ "1" == "$#" ]] ;then
+		ssh -i ~/.ssh/aws.rsa admin@$1
 	else
 		>&2 echo "Missing host argument"
 	fi
 }
 
+ssho () {
+	if [[ "1" == "$#" ]] ;then
+		ssh -i ~/.ssh/omni.rsa ec2-user@$1
+	else
+		>&2 echo "Missing host argument"
+	fi
+}
 
 export POSPS1=' "\\\$ "'
 if [[ -z "$TARGET_ENV" ]]; then
@@ -63,12 +75,11 @@ else
            >&2 echo "Environment configuration file ~/env/${TARGET_ENV} does not exist"
         fi
 fi
-#export COREPS1='"\A \[\e[36m\]\u\[\e[0;31m\]@\h\[\e[0;31m\]\[\e[m\]:[\[\e[1;30m\]\w\[\e[m\] \$(__k8s_prompt)\$(__aws_prompt)]"'
-export COREPS1='"\A \[\e[36m\]\$(__k8s_prompt)\[\e[0;31m\]@\$(__aws_prompt)\[\e[0;31m\]\[\e[m\]:[\[\e[1;30m\]\w\e[m ]"'
+export COREPS1='"\A \[\e[36m\]\$(__k8s_prompt $?)\[\e[0;31m\]\$(__prompt_command)\$(__aws_prompt)\[\e[0;31m\]\[\e[m\]:[\[\e[1;30m\]\w\e[m ]"'
 export PREPS1='__git_ps1 '
 export GIT_PS1_SHOWDIRTYSTATE=0
 export GIT_PS1_SHOWSTASHSTATE=0
-export GIT_PS1_SHOWUNTRACKEDFILES=1
+export GIT_PS1_SHOWUNTRACKEDFILES=
 export GIT_PS1_SHOWCOLORHINTS=1
 export GIT_PS1_DESCRIBE_STYLE="branch"
 export GIT_PS1_SHOWUPSTREAM="auto git"
